const FORM_INFO = {
  DEFAULT_SCREEN_TITLE: "기본정보",
  DEFAULT_SCREEN_GENDER: "성별",
  DEFAULT_SCREEN_MAN: "남성",
  DEFAULT_SCREEN_WOMAN: "여성",
  DEFAULT_SCREEN_AGE: "나이",
  DEFAULT_SCREEN_AGE_MESSAGE: "나이를 입력해주세요.",
  DEFAULT_SCREEN_WEIGHT: "몸무게",
  DEFAULT_SCREEN_WEIGHT_MESSAGE: "몸무게를 입력해주세요.",
  DEFAULT_SCREEN_WEIGHT_UNIT: "kg",
  DEFAULT_SCREEN_HEIGHT: "키",
  DEFAULT_SCREEN_HEIGHT_MESSAGE: "키를 입력해주세요.",
  DEFAULT_SCREEN_HEIGHT_UNIT: "cm",
}

export default FORM_INFO;